language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../mp2-lab10-arithmetics
  - make -j
  - cd ./bin/
  - ./test/Arith_test
notifications:
  email: false
